@PACKAGE_INIT@

set(GLOVE_VERSION @GLOVE_VERSION@)

find_package(Threads REQUIRED)
find_package(Boost 1.55 REQUIRED COMPONENTS thread system date_time filesystem log log_setup)
find_package(ZLIB 1.2.8 REQUIRED)
find_package(PNG 1.6 REQUIRED)
find_package(LibZip 0.11.2 REQUIRED)
find_package(PythonLibs 3.4 REQUIRED)
find_package(TCLAP 1.2.1 REQUIRED)
find_package(YamlCpp 0.5.1 REQUIRED)

set(GLOVE_INCLUDE_DIRS @PACKAGE_INCLUDE_INSTALL_DIR@ ${Boost_INCLUDE_DIRS} ${ZLIB_INCLUDE_DIRS} ${PNG_INCLUDE_DIRS} ${LIBZIP_INCLUDE_DIRS} ${TCLAP_INCLUDE_DIRS} ${YAMLCPP_INCLUDE_DIRS})
set(GLOVE_LIBRARIES @PACKAGE_LIB_INSTALL_DIR@/libglove.so ${Boost_LIBRARIES} ${ZLIB_LIBRARIES} ${PNG_LIBRARIES} ${LIBZIP_LIBRARIES} ${YAMLCPP_LIBRARIES})

set(GLOVE_MODULE_GLRENDERER libmod_glrenderer.so)
set(GLOVE_MODULE_GLRENDERER_LIB @PACKAGE_MODULE_INSTALL_DIR@/${GLOVE_MODULE_GLRENDERER})